### PR TITLE
feat/149-arm-images: update Dockerfile to allow for multi-arch images

### PR DESCRIPTION
**Pull request by Gearheads**
#### What does this PR do?
This PR will update the `Dockerfile` in order to build, and create, multi-arch images. This should enable users to run this `metric-agent` within ARM architecture.
#### Where should the reviewer start?
The reviewer should start with the `Dockerfile` and `Makefile`. That is where most of the changes are located.
#### How should this be manually tested?
This can be manually tested. I am not sure if there is any automation setup for releasing new binaries and images.
#### What picture best describes this PR (optional but encouraged)?
No current Docker image is supporting ARM: https://hub.docker.com/r/cloudability/metrics-agent/tags
Screen Shot 2022-03-14 at 6 32 08 PM

#### What are the relevant Github Issues?
This should fix and close this issue: #149
#### Developer Done List

- [ ] Tests Added/Updated
- [ ] Updated README.md
- [ ] Verified backward compatible
- [ ] Verified database migrations will not be catastrophic
- [ ] Considered Security, Availability and Confidentiality

#### Reviewer/Approval Done List

- [ ] Tests Pass Locally
- [ ] CI Build Passes
- [ ] Verified README.md is updated
- [ ] Verified changes are backward compatible
- [ ] Reviewed impact to Security, Availability and Confidentiality (if issue found, add comments and request changes)

### CODE REVIEW

**Comment by rrobb6** [comment]
Hello @Gearheads - thank you for your PR. Just to let you know, we are currently working on this issue and hope to have a fix out with ARM images shortly.  I'm going to close this PR while we work on this issue.  Thank you.

**Comment by Gearheads** [comment]
Oh ok, thanks @rrobb6. I was told this change was not going to be worked on, so figured I would assist, but glad to hear that it is not the case.

**Comment by rrobb6** [comment]
Nope, definitely working on it right now 😄   Thanks for your assistance, we hope to have the fix out soon!

**Comment by Gearheads** [comment]
ok great! Apologies again for the confusion.

**Pull request closed without merging**
