### PR TITLE
Adding ability to set/override the namespace

### PR DESCRIPTION
**Pull request by daviddyball**
#### What does this PR do?

Adds an option to allow you to specify the namespace which the metrics-agent will run in.

#### Where should the reviewer start?
Try deploying to a namespace other than `cloudability` and setting the `--namespace` flag accordingly

#### How should this be manually tested?

`metrics-agent kubernetes --namespace=some-namespace`

#### Any background context you want to provide?

https://github.com/cloudability/metrics-agent/issues/18

#### What picture best describes this PR (optional but encouraged)?

image

#### Developer Done List

- [x] Tests Added/Updated
- [x] Updated README.md
- [ ] Verified backward compatible
- [ ] Verified database migrations will not be catastrophic
- [x] Considered Security, Availability and Confidentiality

#### Reviewer/Approval Done List

- [ ] Tests Pass Locally
- [ ] CI Build Passes
- [ ] Verified README.md is updated
- [ ] Verified changes are backward compatible
- [ ] Reviewed impact to Security, Availability and Confidentiality (if issue found, add comments and request changes)

### CODE REVIEW

**Comment by daviddyball** [comment]
Not sure how to go about testing backwards compatibility or test the database migrations. Can anyone else help?

**Comment by DavidXArnold** [comment]
@daviddyball thank you for submitting! This looks good. We are in process of adding a contributor license agreement and hope to have an update next week.  We will ping you once it is post.

**Comment by DavidXArnold** [comment]
@daviddyball No need to worry about the compatibility test or database migrations. We now have a CLA process in place. Can you please accept it via the link here?

**Comment by daviddyball** [comment]
@DavidXArnold I think you forgot the link? 😛

**Comment by daviddyball** [comment]
@DavidXArnold Signed 👍

**Pull request merged**
