### PR TITLE
sample cloudability helm chart

### PR DESCRIPTION
**Pull request by kratos81**
#### What does this PR do?
Adds a cloudability helm chart 
#### Developer Done List

- [ ] Tests Added/Updated
- [ ] Updated README.md
- [ ] Verified backward compatible
- [ ] Verified database migrations will not be catastrophic
- [ ] Considered Security, Availability and Confidentiality

#### Reviewer/Approval Done List

- [ ] Tests Pass Locally
- [ ] CI Build Passes
- [ ] Verified README.md is updated
- [ ] Verified changes are backward compatible
- [ ] Reviewed impact to Security, Availability and Confidentiality (if issue found, add comments and request changes)

### CODE REVIEW

**Comment by DavidXArnold** [comment]
thanks @kratos81 !  This looks great. We will take a look at it.  The linting is failing due to a change in gometaliner that we need to handle.

**Comment by DavidXArnold** [comment]
@kratos81 thank you again for submitting! We are in process of adding a contributor license agreement and hope to have an update next week.  We will ping you once it is posted.

**Comment by DavidXArnold** [comment]
@kratos81  Sorry for the delay on this, we now have a CLA process in place. Can you please accept it via the link here?

**Comment by udangel-r7** [comment]
would it be possible to get a helm chart for the agent?

**Comment by DavidXArnold** [comment]
Closing as this is out of date and incompatible with the agent at this point. @udangel-r7 created: https://github.com/cloudability/metrics-agent/issues/40 to request the creation of a helm chart for the metrics-agent.

CC: @caseydoran

**Pull request closed without merging**
