### PR TITLE
Adding support for Helm

### PR DESCRIPTION
**Pull request by lareeth**
#### What does this PR do?
Adds the files required for packaging and publishing a helm chart

#### Where should the reviewer start?
The added charts are in  `deploy/charts`

#### How should this be manually tested?
Using `helm package` or `helm template` or `make helm-package`

To test default settings
`helm template metrics-agent deploy/charts/metrics-agent`

To test with RBAC disabled
`helm template metrics-agent deploy/charts/metrics-agent --set rbac.create=false`

To test with RBAC and the service account disabled
`helm template metrics-agent deploy/charts/metrics-agent --set rbac.create=false --set serviceAccount.create=false`

#### What are the relevant Github Issues?
https://github.com/cloudability/metrics-agent/issues/40

#### Developer Done List

- [ ] Tests Added/Updated
- [ ] Updated README.md
- [ ] Verified backward compatible
- [ ] Verified database migrations will not be catastrophic
- [ ] Considered Security, Availability and Confidentiality

#### Reviewer/Approval Done List

- [ ] Tests Pass Locally
- [ ] CI Build Passes
- [ ] Verified README.md is updated
- [ ] Verified changes are backward compatible
- [ ] Reviewed impact to Security, Availability and Confidentiality (if issue found, add comments and request changes)

### CODE REVIEW

**Comment by lareeth** [comment]
Where do we want to publish these helm packages? Other provides use the `helm repo index` capability and then have a repo with github pages enabled where the helm charts can be installed from

**Comment by shabbirdbz** [comment]
This chart doesn't have required RBAC like Role, Rolebinding, ClusterRole, ClusterRoleBinding required by the metric agent

**Comment by lareeth** [comment]
This was based on the example provided in the repo https://github.com/cloudability/metrics-agent/blob/master/deploy/kubernetes/cloudability-metrics-agent.yaml

I will add the additional resources needed to run

**Comment by DavidXArnold** [comment]
Thanks @lareeth ! PR #78 was just merged and has the appropriate RBAC rules in https://github.com/cloudability/metrics-agent/blob/master/deploy/kubernetes/cloudability-metrics-agent.yaml now.  When you are ready for review please remove the WIP label from the title of the PR and ping here.

Thanks again for your contribution!

**Comment by lareeth** [comment]
I have added the templates for RBAC based on https://github.com/cloudability/metrics-agent/pull/78

I also updated how to test section above to include with RBAC and without

**Comment by lareeth** [comment]
@DavidXArnold Are you able to trigger the build, as it fails due to 
```
snyk_scan - Unauthorized
```

**Comment by lareeth** [comment]
Theres still the discussion of where you want to publish these, as this adds the charts and publish scripts, but doesnt actually publish anywhere

**Comment by lareeth** [comment]
Theres still the discussion of where you want to publish these, as this adds the charts and publish scripts, but doesnt actually publish anywhere

**Comment by djsly** [comment]
@lareeth where can I find your chart repo to properly perform `helm install`

**Pull request merged**
