### PR TITLE
Adds 1.21 end to end test

### PR DESCRIPTION
**Pull request by cadams8238**
#### What does this PR do?
See title.

#### Where should the reviewer start?
A note about the extra commits seen here - the beta branch hasn't been kept up with master so all commits up to "add 1.21.1 e2e test + update test-e2e-all" are catching-up-to-master commits. The final 3 commits are the ones pertinent to review.

#### How should this be manually tested?
Run `make test-e2e-1.21.1` and `make test-e2e-all`

#### Any background context you want to provide?
Nope.

#### What picture best describes this PR (optional but encouraged)?
testing

#### What are the relevant Github Issues?
None.

#### Developer Done List

- [ ] Tests Added/Updated
- [ ] Updated README.md
- [X] Verified backward compatible
- [ ] Verified database migrations will not be catastrophic
- [X] Considered Security, Availability and Confidentiality

#### Reviewer/Approval Done List

- [ ] Tests Pass Locally
- [ ] CI Build Passes
- [ ] Verified README.md is updated
- [ ] Verified changes are backward compatible
- [ ] Reviewed impact to Security, Availability and Confidentiality (if issue found, add comments and request changes)

### CODE REVIEW

**Review by rrobb6 — COMMENTED** [review]
Looks like the beta branch is way behind master. We should probably rebase beta off of master first so that we know what you're changes really are?

**Comment by cadams8238** [comment]
My changes are the last 3 commits. When you say "rebase beta off of master", do you mean spin up another PR with just catching up beta with master? Or is the beta branch not locked down like master and I can rebase and push to it directly?

**Review by rrobb6 — COMMENTED** [review]
Beta branch is not locked down, so we can just update it.  We do do the PR process for it for new changes though so that we can review all the changes piece by piece.

**Comment by cadams8238** [comment]
Ah! Ok, I'll get it caught up then. Thank you for clarifying!

**Comment by cadams8238** [comment]
Closing and re-opening to get the latest updated beta branch

**Pull request closed without merging**
